/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace semisorted_arnerve
{
    public sealed class herder_user_t : LCM.LCM.LCMEncodable
    {
        public long timestamp;
        public short NUM_USERS;
        public semisorted_arnerve.user_update_t[] users;
 
        public herder_user_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x6c1e8b1b6b5c3ffcL;
 
        static herder_user_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("semisorted_arnerve.herder_user_t"))
                return 0L;
 
            classes.Add("semisorted_arnerve.herder_user_t");
            ulong hash = LCM_FINGERPRINT_BASE
                 + semisorted_arnerve.user_update_t._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.timestamp); 
 
            outs.Write(this.NUM_USERS); 
 
            for (int a = 0; a < this.NUM_USERS; a++) {
                this.users[a]._encodeRecursive(outs); 
            }
 
        }
 
        public herder_user_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public herder_user_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static semisorted_arnerve.herder_user_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            semisorted_arnerve.herder_user_t o = new semisorted_arnerve.herder_user_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.timestamp = ins.ReadInt64();
 
            this.NUM_USERS = ins.ReadInt16();
 
            this.users = new semisorted_arnerve.user_update_t[(int) NUM_USERS];
            for (int a = 0; a < this.NUM_USERS; a++) {
                this.users[a] = semisorted_arnerve.user_update_t._decodeRecursiveFactory(ins);
            }
 
        }
 
        public semisorted_arnerve.herder_user_t Copy()
        {
            semisorted_arnerve.herder_user_t outobj = new semisorted_arnerve.herder_user_t();
            outobj.timestamp = this.timestamp;
 
            outobj.NUM_USERS = this.NUM_USERS;
 
            outobj.users = new semisorted_arnerve.user_update_t[(int) NUM_USERS];
            for (int a = 0; a < this.NUM_USERS; a++) {
                outobj.users[a] = this.users[a].Copy();
            }
 
            return outobj;
        }
    }
}

