/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package semisorted_arnerve;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class kinect_update_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public byte issourceupdating;
    public double torsoposition[];
    public double forwardvec[];
    public double rightvec[];
    public byte is_rhandclosed;
    public byte is_lhandclosed;
    public double rhandposition[];
    public double lhandposition[];
    public double headorientation[];
    public double headposition[];
    public semisorted_arnerve.kinect_rawdata_t rawkinectdata;
 
    public kinect_update_t()
    {
        torsoposition = new double[3];
        forwardvec = new double[3];
        rightvec = new double[3];
        rhandposition = new double[3];
        lhandposition = new double[3];
        headorientation = new double[3];
        headposition = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x86bc047dbcd6d578L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(semisorted_arnerve.kinect_update_t.class))
            return 0L;
 
        classes.add(semisorted_arnerve.kinect_update_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + semisorted_arnerve.kinect_rawdata_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeByte(this.issourceupdating); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.torsoposition[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.forwardvec[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.rightvec[a]); 
        }
 
        outs.writeByte(this.is_rhandclosed); 
 
        outs.writeByte(this.is_lhandclosed); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.rhandposition[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.lhandposition[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.headorientation[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.headposition[a]); 
        }
 
        this.rawkinectdata._encodeRecursive(outs); 
 
    }
 
    public kinect_update_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public kinect_update_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static semisorted_arnerve.kinect_update_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        semisorted_arnerve.kinect_update_t o = new semisorted_arnerve.kinect_update_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.issourceupdating = ins.readByte();
 
        this.torsoposition = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.torsoposition[a] = ins.readDouble();
        }
 
        this.forwardvec = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.forwardvec[a] = ins.readDouble();
        }
 
        this.rightvec = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rightvec[a] = ins.readDouble();
        }
 
        this.is_rhandclosed = ins.readByte();
 
        this.is_lhandclosed = ins.readByte();
 
        this.rhandposition = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rhandposition[a] = ins.readDouble();
        }
 
        this.lhandposition = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.lhandposition[a] = ins.readDouble();
        }
 
        this.headorientation = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.headorientation[a] = ins.readDouble();
        }
 
        this.headposition = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.headposition[a] = ins.readDouble();
        }
 
        this.rawkinectdata = semisorted_arnerve.kinect_rawdata_t._decodeRecursiveFactory(ins);
 
    }
 
    public semisorted_arnerve.kinect_update_t copy()
    {
        semisorted_arnerve.kinect_update_t outobj = new semisorted_arnerve.kinect_update_t();
        outobj.timestamp = this.timestamp;
 
        outobj.issourceupdating = this.issourceupdating;
 
        outobj.torsoposition = new double[(int) 3];
        System.arraycopy(this.torsoposition, 0, outobj.torsoposition, 0, 3); 
        outobj.forwardvec = new double[(int) 3];
        System.arraycopy(this.forwardvec, 0, outobj.forwardvec, 0, 3); 
        outobj.rightvec = new double[(int) 3];
        System.arraycopy(this.rightvec, 0, outobj.rightvec, 0, 3); 
        outobj.is_rhandclosed = this.is_rhandclosed;
 
        outobj.is_lhandclosed = this.is_lhandclosed;
 
        outobj.rhandposition = new double[(int) 3];
        System.arraycopy(this.rhandposition, 0, outobj.rhandposition, 0, 3); 
        outobj.lhandposition = new double[(int) 3];
        System.arraycopy(this.lhandposition, 0, outobj.lhandposition, 0, 3); 
        outobj.headorientation = new double[(int) 3];
        System.arraycopy(this.headorientation, 0, outobj.headorientation, 0, 3); 
        outobj.headposition = new double[(int) 3];
        System.arraycopy(this.headposition, 0, outobj.headposition, 0, 3); 
        outobj.rawkinectdata = this.rawkinectdata.copy();
 
        return outobj;
    }
 
}

