"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import bool

import kinect_rawdata_t

class kinect_update_t(object):
    __slots__ = ["timestamp", "torsoposition", "forwardvec", "rightvec", "is_rhandclosed", "is_lhandclosed", "rhandposition", "lhandposition", "headorientation", "headposition", "rawkinectdata"]

    def __init__(self):
        self.timestamp = 0
        self.torsoposition = [ 0.0 for dim0 in range(3) ]
        self.forwardvec = [ 0.0 for dim0 in range(3) ]
        self.rightvec = [ 0.0 for dim0 in range(3) ]
        self.is_rhandclosed = None
        self.is_lhandclosed = None
        self.rhandposition = [ 0.0 for dim0 in range(3) ]
        self.lhandposition = [ 0.0 for dim0 in range(3) ]
        self.headorientation = [ 0.0 for dim0 in range(3) ]
        self.headposition = [ 0.0 for dim0 in range(3) ]
        self.rawkinectdata = None

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(kinect_update_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>3d', *self.torsoposition[:3]))
        buf.write(struct.pack('>3d', *self.forwardvec[:3]))
        buf.write(struct.pack('>3d', *self.rightvec[:3]))
        assert self.is_rhandclosed._get_packed_fingerprint() == bool.bool._get_packed_fingerprint()
        self.is_rhandclosed._encode_one(buf)
        assert self.is_lhandclosed._get_packed_fingerprint() == bool.bool._get_packed_fingerprint()
        self.is_lhandclosed._encode_one(buf)
        buf.write(struct.pack('>3d', *self.rhandposition[:3]))
        buf.write(struct.pack('>3d', *self.lhandposition[:3]))
        buf.write(struct.pack('>3d', *self.headorientation[:3]))
        buf.write(struct.pack('>3d', *self.headposition[:3]))
        assert self.rawkinectdata._get_packed_fingerprint() == kinect_rawdata_t.kinect_rawdata_t._get_packed_fingerprint()
        self.rawkinectdata._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != kinect_update_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return kinect_update_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = kinect_update_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.torsoposition = struct.unpack('>3d', buf.read(24))
        self.forwardvec = struct.unpack('>3d', buf.read(24))
        self.rightvec = struct.unpack('>3d', buf.read(24))
        self.is_rhandclosed = bool.bool._decode_one(buf)
        self.is_lhandclosed = bool.bool._decode_one(buf)
        self.rhandposition = struct.unpack('>3d', buf.read(24))
        self.lhandposition = struct.unpack('>3d', buf.read(24))
        self.headorientation = struct.unpack('>3d', buf.read(24))
        self.headposition = struct.unpack('>3d', buf.read(24))
        self.rawkinectdata = kinect_rawdata_t.kinect_rawdata_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if kinect_update_t in parents: return 0
        newparents = parents + [kinect_update_t]
        tmphash = (0xfb7315ec0b92ddfa+ bool.bool._get_hash_recursive(newparents)+ bool.bool._get_hash_recursive(newparents)+ kinect_rawdata_t.kinect_rawdata_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if kinect_update_t._packed_fingerprint is None:
            kinect_update_t._packed_fingerprint = struct.pack(">Q", kinect_update_t._get_hash_recursive([]))
        return kinect_update_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

