/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package semisorted_arnerve;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class oculus_update_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public byte issourceupdating;
    public double headorientation[];
    public double headposition[];
 
    public oculus_update_t()
    {
        headorientation = new double[3];
        headposition = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8e7c72b02ec1b040L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(semisorted_arnerve.oculus_update_t.class))
            return 0L;
 
        classes.add(semisorted_arnerve.oculus_update_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeByte(this.issourceupdating); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.headorientation[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.headposition[a]); 
        }
 
    }
 
    public oculus_update_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public oculus_update_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static semisorted_arnerve.oculus_update_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        semisorted_arnerve.oculus_update_t o = new semisorted_arnerve.oculus_update_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.issourceupdating = ins.readByte();
 
        this.headorientation = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.headorientation[a] = ins.readDouble();
        }
 
        this.headposition = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.headposition[a] = ins.readDouble();
        }
 
    }
 
    public semisorted_arnerve.oculus_update_t copy()
    {
        semisorted_arnerve.oculus_update_t outobj = new semisorted_arnerve.oculus_update_t();
        outobj.timestamp = this.timestamp;
 
        outobj.issourceupdating = this.issourceupdating;
 
        outobj.headorientation = new double[(int) 3];
        System.arraycopy(this.headorientation, 0, outobj.headorientation, 0, 3); 
        outobj.headposition = new double[(int) 3];
        System.arraycopy(this.headposition, 0, outobj.headposition, 0, 3); 
        return outobj;
    }
 
}

