"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class oculus_update_t(object):
    __slots__ = ["timestamp", "headorientation", "headposition"]

    def __init__(self):
        self.timestamp = 0
        self.headorientation = [ 0.0 for dim0 in range(3) ]
        self.headposition = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(oculus_update_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>3d', *self.headorientation[:3]))
        buf.write(struct.pack('>3d', *self.headposition[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != oculus_update_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return oculus_update_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = oculus_update_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.headorientation = struct.unpack('>3d', buf.read(24))
        self.headposition = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if oculus_update_t in parents: return 0
        tmphash = (0x2168a8d99c85d900) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if oculus_update_t._packed_fingerprint is None:
            oculus_update_t._packed_fingerprint = struct.pack(">Q", oculus_update_t._get_hash_recursive([]))
        return oculus_update_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

