/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace semisorted_arnerve
{
    public sealed class role_response_t : LCM.LCM.LCMEncodable
    {
        public long timestamp;
        public semisorted_arnerve.user_update_t originalRequest;
        public byte isAccepted;
 
        public role_response_t()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xe980dfe2805f736bL;
 
        static role_response_t()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("semisorted_arnerve.role_response_t"))
                return 0L;
 
            classes.Add("semisorted_arnerve.role_response_t");
            ulong hash = LCM_FINGERPRINT_BASE
                 + semisorted_arnerve.user_update_t._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.timestamp); 
 
            this.originalRequest._encodeRecursive(outs); 
 
            outs.Write(this.isAccepted); 
 
        }
 
        public role_response_t(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public role_response_t(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static semisorted_arnerve.role_response_t _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            semisorted_arnerve.role_response_t o = new semisorted_arnerve.role_response_t();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.timestamp = ins.ReadInt64();
 
            this.originalRequest = semisorted_arnerve.user_update_t._decodeRecursiveFactory(ins);
 
            this.isAccepted = ins.ReadByte();
 
        }
 
        public semisorted_arnerve.role_response_t Copy()
        {
            semisorted_arnerve.role_response_t outobj = new semisorted_arnerve.role_response_t();
            outobj.timestamp = this.timestamp;
 
            outobj.originalRequest = this.originalRequest.Copy();
 
            outobj.isAccepted = this.isAccepted;
 
            return outobj;
        }
    }
}

