"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import user_update_t

class role_response_t(object):
    __slots__ = ["timestamp", "originalRequest", "isAccepted"]

    def __init__(self):
        self.timestamp = 0
        self.originalRequest = None
        self.isAccepted = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(role_response_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        assert self.originalRequest._get_packed_fingerprint() == user_update_t.user_update_t._get_packed_fingerprint()
        self.originalRequest._encode_one(buf)
        buf.write(struct.pack(">b", self.isAccepted))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != role_response_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return role_response_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = role_response_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.originalRequest = user_update_t.user_update_t._decode_one(buf)
        self.isAccepted = struct.unpack(">b", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if role_response_t in parents: return 0
        newparents = parents + [role_response_t]
        tmphash = (0xe980dfe2805f736b+ user_update_t.user_update_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if role_response_t._packed_fingerprint is None:
            role_response_t._packed_fingerprint = struct.pack(">Q", role_response_t._get_hash_recursive([]))
        return role_response_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

