"""LCM package __init__.py file
This file automatically generated by lcm-gen.
DO NOT MODIFY BY HAND!!!!
"""

from bot_control_command_t import bot_control_command_t
from bot_update_t import bot_update_t
