"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class bot_update_t(object):
    __slots__ = ["timestamp", "name", "numBytes_cameraFrameJpeg", "cameraFrameJpeg", "batteryPercentage"]

    def __init__(self):
        self.timestamp = 0
        self.name = ""
        self.numBytes_cameraFrameJpeg = 0
        self.cameraFrameJpeg = []
        self.batteryPercentage = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(bot_update_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.timestamp))
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write("\0")
        buf.write(struct.pack(">i", self.numBytes_cameraFrameJpeg))
        buf.write(self.cameraFrameJpeg[:self.numBytes_cameraFrameJpeg])
        buf.write(struct.pack(">f", self.batteryPercentage))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != bot_update_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return bot_update_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = bot_update_t()
        self.timestamp = struct.unpack(">i", buf.read(4))[0]
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.numBytes_cameraFrameJpeg = struct.unpack(">i", buf.read(4))[0]
        self.cameraFrameJpeg = buf.read(self.numBytes_cameraFrameJpeg)
        self.batteryPercentage = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if bot_update_t in parents: return 0
        tmphash = (0x45d643a2c5ff1d60) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if bot_update_t._packed_fingerprint is None:
            bot_update_t._packed_fingerprint = struct.pack(">Q", bot_update_t._get_hash_recursive([]))
        return bot_update_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

